In [5]:
import pandas as pd
df=pd.read_csv('customer_shopping_behavior.csv')

In [6]:
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   object
 3   Item Purchased          3900 non-null   object
 4   Category                3900 non-null   object
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   object
 7   Size                    3900 non-null   object
 8   Color                   3900 non-null   object
 9   Season                  3900 non-null   object
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   object
 12  Shipping Type           3900 non-null   object
 13  Discount Applied        3900 non-null   object
 14  Promo Code Used         3900 non-null   object
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   object
 17  Frequency of Purchases  3900 non-null   object
dtypes: float64(1), int64(4), object(13)
memory usage: 548.6+ KB

In [10]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [11]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [13]:
df['Review Rating']=df.groupby('Category')['Review Rating'].transform(lambda x:x.fillna(x.median()))

In [14]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [19]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')

In [20]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [22]:
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount'})

In [23]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='object')

In [24]:
#creating a new column
labels=['Young Adult','Adult','Middle-aged','Senior']
df['age_group']=pd.qcut(df['age'],q=4,labels=labels)

In [25]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [31]:

frequency_mapping={
    'Fortnightly':14,
    'Weekly':7,
    'Monthly':30,
    'Quarterly':90,
    'Bi-Weekly':14,
    'Annually':365,
    'Every 3 Months':90
}
df['Purchase_frequency_days']=df['frequency_of_purchases'].map(frequency_mapping)

In [32]:
df[['frequency_of_purchases','Purchase_frequency_days']].head(10)

  frequency_of_purchases  Purchase_frequency_days
0            Fortnightly                       14
1            Fortnightly                       14
2                 Weekly                        7
3                 Weekly                        7
4               Annually                      365
5                 Weekly                        7
6              Quarterly                       90
7                 Weekly                        7
8               Annually                      365
9              Quarterly                       90

In [33]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [37]:
#checking if both these columns are redundant
(df['discount_applied']==df['promo_code_used']).all()

np.True_

In [38]:
df=df.drop('promo_code_used',axis=1)

In [39]:
pip install sqlalchemy jupysql psycopg2-binary

Requirement already satisfied: sqlalchemy in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (2.0.40)
Collecting jupysql
  Downloading jupysql-0.11.1-py3-none-any.whl.metadata (5.9 kB)
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Requirement already satisfied: greenlet>=1 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (3.2.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.13.2)
Collecting prettytable>=3.12.0 (from jupysql)
  Downloading prettytable-3.17.0-py3-none-any.whl.metadata (34 kB)
Collecting sqlparse (from jupysql)
  Downloading sqlparse-0.5.5-py3-none-any.whl.metadata (4.7 kB)
Collecting ipython-genutils>=0.1.0 (from jupysql)
  Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl.metadata (755 bytes)
Requirement already satisfied: jinja2 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from jupysql) (3.1.6)
Collecting sqlglot>=11.3.7 (from jupysql)
  Downloading sqlglot-29.0.1-py3-none-any.whl.metadata (22 kB)
Collecting jupysql-plugin>=0.4.2 (from jupysql)
  Downloading jupysql_plugin-0.4.5-py3-none-any.whl.metadata (7.8 kB)
Collecting ploomber-core>=0.2.7 (from jupysql)
  Downloading ploomber_core-0.2.27-py3-none-any.whl.metadata (532 bytes)
Requirement already satisfied: pyyaml in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from ploomber-core>=0.2.7->jupysql) (6.0.2)
Collecting posthog>=3.0 (from ploomber-core>=0.2.7->jupysql)
  Downloading posthog-7.9.6-py3-none-any.whl.metadata (6.4 kB)
Requirement already satisfied: requests<3.0,>=2.7 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.32.3)
Requirement already satisfied: six>=1.5 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.17.0)
Requirement already satisfied: python-dateutil>=2.2 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.9.0.post0)
Collecting backoff>=1.10.0 (from posthog>=3.0->ploomber-core>=0.2.7->jupysql)
  Using cached backoff-2.2.1-py3-none-any.whl.metadata (14 kB)
Requirement already satisfied: distro>=1.5.0 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from posthog>=3.0->ploomber-core>=0.2.7->jupysql) (1.9.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2.4.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from requests<3.0,>=2.7->posthog>=3.0->ploomber-core>=0.2.7->jupysql) (2025.1.31)
Requirement already satisfied: wcwidth in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from prettytable>=3.12.0->jupysql) (0.2.13)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\apoor\appdata\local\programs\python\python312\lib\site-packages (from jinja2->jupysql) (3.0.2)
Downloading jupysql-0.11.1-py3-none-any.whl (95 kB)
Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   --- ------------------------------------ 0.3/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 1.4 MB/s eta 0:00:02
   ----------- ---------------------------- 0.8/2.7 MB 1.3 MB/s eta 0:00:02
   --------------- ------------------------ 1.0/2.7 MB 1.3 MB/s eta 0:00:02
   ------------------- -------------------- 1.3/2.7 MB 1.3 MB/s eta 0:00:02
   ----------------------- ---------------- 1.6/2.7 MB 1.3 MB/s eta 0:00:01
   --------------------------- ------------ 1.8/2.7 MB 1.3 MB/s eta 0:00:01
   ------------------------------ --------- 2.1/2.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 1.3 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 1.3 MB/s  0:00:02
Downloading ipython_genutils-0.2.0-py2.py3-none-any.whl (26 kB)
Downloading jupysql_plugin-0.4.5-py3-none-any.whl (192 kB)
Downloading ploomber_core-0.2.27-py3-none-any.whl (22 kB)
Downloading posthog-7.9.6-py3-none-any.whl (201 kB)
Using cached backoff-2.2.1-py3-none-any.whl (15 kB)
Downloading prettytable-3.17.0-py3-none-any.whl (34 kB)
Downloading sqlglot-29.0.1-py3-none-any.whl (611 kB)
   ---------------------------------------- 0.0/611.4 kB ? eta -:--:--
   ----------------- ---------------------- 262.1/611.4 kB ? eta -:--:--
   ---------------------------------------- 611.4/611.4 kB 1.2 MB/s  0:00:00
Downloading sqlparse-0.5.5-py3-none-any.whl (46 kB)
Installing collected packages: ipython-genutils, sqlparse, sqlglot, psycopg2-binary, prettytable, backoff, posthog, ploomber-core, jupysql-plugin, jupysql

   ----------------------------------------  0/10 [ipython-genutils]
   ----------------------------------------  0/10 [ipython-genutils]
   ----------------------------------------  0/10 [ipython-genutils]
   ---- -----------------------------------  1/10 [sqlparse]
   ---- -----------------------------------  1/10 [sqlparse]
   ---- -----------------------------------  1/10 [sqlparse]
   ---- -----------------------------------  1/10 [sqlparse]
   ---- -----------------------------------  1/10 [sqlparse]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   -------- -------------------------------  2/10 [sqlglot]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ------------ ---------------------------  3/10 [psycopg2-binary]
   ---------------- -----------------------  4/10 [prettytable]
   -------------------- -------------------  5/10 [backoff]
   -------------------- -------------------  5/10 [backoff]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ------------------------ ---------------  6/10 [posthog]
   ---------------------------- -----------  7/10 [ploomber-core]
   ---------------------------- -----------  7/10 [ploomber-core]
   ---------------------------- -----------  7/10 [ploomber-core]
   -------------------------------- -------  8/10 [jupysql-plugin]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ------------------------------------ ---  9/10 [jupysql]
   ---------------------------------------- 10/10 [jupysql]

Successfully installed backoff-2.2.1 ipython-genutils-0.2.0 jupysql-0.11.1 jupysql-plugin-0.4.5 ploomber-core-0.2.27 posthog-7.9.6 prettytable-3.17.0 psycopg2-binary-2.9.11 sqlglot-29.0.1 sqlparse-0.5.5
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [40]:
%load_ext sql
from sqlalchemy import create_engine

In [41]:
# 4) Create/connect SQLite database file
engine = create_engine("sqlite:///shopping.db")

# 5) Write DataFrame to SQL table
df.to_sql("customer_shopping", engine, if_exists="replace", index=False)
print("Loaded rows:", len(df))

Loaded rows: 3900

In [42]:
# 6) Connect SQL magic to the same SQLite DB
%sql sqlite:///shopping.db

Connecting to 'sqlite:///shopping.db'

In [44]:
%sql SELECT COUNT(*) FROM customer_shopping limit 20

Running query in 'sqlite:///shopping.db'

+----------+
| COUNT(*) |
+----------+
|   3900   |
+----------+

In [48]:
# Q.1) what is the revenue generated by male vs female customers?
query = "SELECT gender, SUM(purchase_amount) as revenue FROM customer_shopping GROUP BY gender"
result = pd.read_sql_query(query, engine)
result

   gender  revenue
0  Female    75191
1    Male   157890

In [53]:
#Q.2) which customer used a discount and had a purchase amount greater than the average purchase amount?
query = """
SELECT customer_id, purchase_amount
FROM customer_shopping
WHERE UPPER(discount_applied) = 'YES'
  AND CAST(purchase_amount AS REAL) > (
      SELECT AVG(CAST(purchase_amount AS REAL))
      FROM customer_shopping
  )
"""
result = pd.read_sql_query(query, engine)
print("rows:", len(result))
result.head(20)

rows: 839

    customer_id  purchase_amount
0             2               64
1             3               73
2             4               90
3             7               85
4             9               97
5            12               68
6            13               72
7            16               81
8            20               90
9            22               62
10           24               88
11           29               94
12           32               79
13           33               67
14           35               91
15           37               69
16           40               60
17           41               76
18           43              100
19           44               69

In [54]:
#Q.3) which are the top 5 products with the highest average review rating?
query = """
SELECT item_purchased, AVG(CAST(review_rating AS REAL)) as avg_rating from customer_shopping
GROUP BY item_purchased
ORDER BY avg_rating DESC
LIMIT 5
"""
result = pd.read_sql_query(query, engine)
result

  item_purchased  avg_rating
0         Gloves    3.861429
1        Sandals    3.844375
2          Boots    3.818750
3            Hat    3.801299
4          Skirt    3.784810

In [55]:
#Q.4) compare the average purchase amounts between standard and express shipping.
query = """
SELECT shipping_type, AVG(CAST(purchase_amount AS REAL)) as avg_purchase  from customer_shopping
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
"""
result = pd.read_sql_query(query, engine)
result

  shipping_type  avg_purchase
0       Express     60.475232
1      Standard     58.460245

In [56]:
#Q.5) do subscribed customers spend more? compare average spend and total revenue between subscribed and non-subscribed customers.
query = """
SELECT subscription_status,
COUNT(customer_id) as total_customers,
AVG(CAST(purchase_amount AS REAL)) as avg_spend,
SUM(CAST(purchase_amount AS REAL)) as total_revenue
FROM customer_shopping
GROUP BY subscription_status
order by total_revenue,avg_spend DESC;
"""
result = pd.read_sql_query(query, engine)
result

  subscription_status  total_customers  avg_spend  total_revenue
0                 Yes             1053  59.491928        62645.0
1                  No             2847  59.865121       170436.0

In [57]:
#Q.6) which 5 products have the highest percentage of purchases with discounts applied?
query = """
select item_purchased,
ROUND(100.0 * SUM(CASE WHEN UPPER(discount_applied) = 'YES' THEN 1 ELSE 0 END) / COUNT(*), 2) as discount_rate
from customer_shopping
group by item_purchased
order by discount_rate DESC
LIMIT 5;
"""
result = pd.read_sql_query(query, engine)
result

  item_purchased  discount_rate
0            Hat          50.00
1       Sneakers          49.66
2           Coat          49.07
3        Sweater          48.17
4          Pants          47.37

In [60]:
#Q.7) segment customers into new, returning, and loyal based on their total number of purchases and show the count of each segment.
query = """
WITH customer_segments AS (
    SELECT customer_id,
           previous_purchases,
           CASE
               WHEN previous_purchases = 1 THEN 'New'
               WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
               ELSE 'Loyal'
           END AS customer_segment
    FROM customer_shopping
)
SELECT customer_segment,
       COUNT(*) AS "Number of Customers"
FROM customer_segments
GROUP BY customer_segment;
"""
result = pd.read_sql_query(query, engine)
result

  customer_segment  Number of Customers
0            Loyal                 3116
1              New                   83
2        Returning                  701

In [61]:
#Q.8) what are the top 3 most purchased products within each category?
query = """
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
row_number() over (partition by category order by count(customer_id) desc) as item_rank
from customer_shopping
group by category, item_purchased
)
select category, item_purchased, item_rank,total_orders
from item_counts
where item_rank <= 3

"""
result = pd.read_sql_query(query, engine)
result

       category item_purchased  item_rank  total_orders
0   Accessories        Jewelry          1           171
1   Accessories     Sunglasses          2           161
2   Accessories           Belt          3           161
3      Clothing          Pants          1           171
4      Clothing         Blouse          2           171
5      Clothing          Shirt          3           169
6      Footwear        Sandals          1           160
7      Footwear          Shoes          2           150
8      Footwear       Sneakers          3           145
9     Outerwear         Jacket          1           163
10    Outerwear           Coat          2           161

In [63]:
#Q.9) are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
query = """
select subscription_status,
count(customer_id) as repeat_buyers
from customer_shopping
where previous_purchases > 5
group by subscription_status
"""
result = pd.read_sql_query(query, engine)
result

  subscription_status  repeat_buyers
0                  No           2518
1                 Yes            958

In [64]:
#Q.10) what is the revenue conntribution of each age group?
query = """
select age_group,
sum(purchase_amount) as total_revenue
from customer_shopping
group by age_group
order by total_revenue desc
"""
result = pd.read_sql_query(query, engine)
result

     age_group  total_revenue
0  Young Adult          62143
1  Middle-aged          59197
2        Adult          55978
3       Senior          55763